@base_url = http://localhost:8000/api

### Register
# @name register
# @prompt username Username (ex: menta)
# @prompt password Password (ex: password123)
POST {{base_url}}/authentication/register
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}",
    "display_name": "{{username}}"
}

### Login
# @name login
# @prompt username Username (ex: menta)
# @prompt password Password (ex: password123)
POST {{base_url}}/authentication/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}
